### ISSUE TITLE
Separate Pact Command Payload from Sign Request generation from signing

### ISSUE THREAD

**Issue by tim-eucalyptus** [Eucalyptus-Labs/KadenaDartSdk#1]
It would be more useful to have the Pact Command Payload (PCP) from Sign Request generation as a separate method and then have a generic signing method which we pass the PCP to be signed. Rather than having it all combined together in one method, that is. For me, I'd like to leverage this PCP from Sign Request translation and do the signing with some other code I have, but as it is rn, I cannot.

**Comment by Luzzotica** [comment]
Resolved with version 2.0.0
